### ISSUE TITLE
isProfane function doesn't work as expected

### ISSUE THREAD

**Issue by MachineThing** [LandonHarter/pyfanity#2]
The `isProfane` function doesn't seem to work as expected.
`pyfanity.isProfane("shit")` returns False through there is a profane word.
However if you turn deepsearch on as so:
`pyfanity.isProfane("shit", True)` returns True as expected.

**Comment by LandonHarter** [comment]
@MachineThing If you look into the source, it is using 2 data sets found on the web. It has the raw file in the repo and even the links to it. All the script does is read these and check for profanity, it is just the dataset.

**Comment by LandonHarter** [comment]
@MachineThing I just found the issue. You are using isProfane, which splits up the string by spaces. Since there are no spaces in one word, shit, it says the array size is 0. To fix this, you can use isWordProfane, and that should work. I will come up with a fix in the meantime.
